//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplicationQLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOAHOC
    {
        public string MAKH { get; set; }
        public string MAGV { get; set; }
        public string MAMH { get; set; }
        public Nullable<System.DateTime> NGAYBD { get; set; }
        public Nullable<System.DateTime> NGAYKY { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual MONHOC MONHOC { get; set; }
    }
}
