//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXApplicationQLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SINHVIEN()
        {
            this.KETQUA = new HashSet<KETQUA>();
        }
    
        public string TENSV { get; set; }
        public string MASV { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string PHAI { get; set; }
        public string MAKHOA { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> DIENTHOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KETQUA> KETQUA { get; set; }
        public virtual KHOA KHOA { get; set; }
    }
}
